/*
 Navicat MySQL Dump SQL

 Source Server         : nice
 Source Server Type    : MySQL
 Source Server Version : 90700 (9.7.0)
 Source Host           : localhost:3306
 Source Schema         : beautiful_elf

 Target Server Type    : MySQL
 Target Server Version : 90700 (9.7.0)
 File Encoding         : 65001

 Date: 23/06/2026 04:08:11
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for tool
-- ----------------------------
DROP TABLE IF EXISTS `tool`;
CREATE TABLE `tool`  (
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '工具名称',
  `display_name` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '显示名称',
  `description` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '工具描述',
  `module` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '所属模块',
  `json_schema` json NOT NULL COMMENT '参数 JSON Schema (MCP inputSchema)',
  `output_schema` json NOT NULL COMMENT '输出 JSON Schema (MCP outputSchema)',
  `risk_level` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'low' COMMENT '风险等级: low/medium/high',
  `is_enabled` tinyint UNSIGNED NOT NULL DEFAULT 1 COMMENT '是否启用: 1=是 0=否',
  `version` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '1.0.0' COMMENT '工具版本号 (FastMCP v3)',
  `timeout_seconds` int UNSIGNED NOT NULL DEFAULT 60 COMMENT '工具执行超时 (秒)',
  `annotations` json NOT NULL COMMENT 'MCP Tool Annotations',
  `is_deleted` tinyint UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否删除: 1=是 0=否',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_tool_name`(`name` ASC) USING BTREE,
  INDEX `idx_tool_module`(`module` ASC) USING BTREE,
  INDEX `idx_tool_is_deleted_enabled`(`is_deleted` ASC, `is_enabled` ASC) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 30 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '工具注册表' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of tool
-- ----------------------------
INSERT INTO `tool` VALUES (1, 'read_file', '读取文件', '读取工作空间中的文件内容，支持文本文件，限制 1MB', 'filesystem', '{\"type\": \"object\", \"required\": [\"path\"], \"properties\": {\"path\": {\"type\": \"string\", \"description\": \"文件路径（相对于工作空间）\"}, \"encoding\": {\"type\": \"string\", \"default\": \"utf-8\", \"description\": \"文件编码\"}}}', '{\"type\": \"object\", \"properties\": {\"error\": {\"type\": \"string\"}, \"content\": {\"type\": \"string\"}}}', 'low', 1, '1.0.0', 30, '{\"readOnlyHint\": true, \"openWorldHint\": false, \"idempotentHint\": true, \"destructiveHint\": false}', 0, '2026-06-13 23:33:47', '2026-06-13 23:33:47');
INSERT INTO `tool` VALUES (2, 'write_file', '写入文件', '创建或覆盖工作空间中的文件，自动创建父目录', 'filesystem', '{\"type\": \"object\", \"required\": [\"path\", \"content\"], \"properties\": {\"path\": {\"type\": \"string\", \"description\": \"文件路径（相对于工作空间）\"}, \"content\": {\"type\": \"string\", \"description\": \"文件内容\"}, \"encoding\": {\"type\": \"string\", \"default\": \"utf-8\"}}}', '{\"type\": \"object\", \"properties\": {\"error\": {\"type\": \"string\"}, \"success\": {\"type\": \"boolean\"}, \"bytes_written\": {\"type\": \"integer\"}}}', 'medium', 1, '1.0.0', 30, '{\"readOnlyHint\": false, \"openWorldHint\": false, \"idempotentHint\": true, \"destructiveHint\": false}', 0, '2026-06-13 23:33:47', '2026-06-13 23:33:47');
INSERT INTO `tool` VALUES (3, 'list_files', '列出文件', '列出工作空间目录下的文件和子目录', 'filesystem', '{\"type\": \"object\", \"properties\": {\"path\": {\"type\": \"string\", \"default\": \".\", \"description\": \"目录路径\"}, \"pattern\": {\"type\": \"string\", \"description\": \"文件名通配符，如 *.py\"}, \"recursive\": {\"type\": \"boolean\", \"default\": false}}}', '{\"type\": \"object\", \"properties\": {\"files\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"properties\": {\"name\": {\"type\": \"string\"}, \"size\": {\"type\": \"integer\"}, \"is_dir\": {\"type\": \"boolean\"}}}}}}', 'low', 1, '1.0.0', 15, '{\"readOnlyHint\": true, \"openWorldHint\": false, \"idempotentHint\": true, \"destructiveHint\": false}', 0, '2026-06-13 23:33:47', '2026-06-13 23:33:47');
INSERT INTO `tool` VALUES (4, 'apply_patch', '应用补丁', '对文件进行精确文本替换（oldText → newText），支持多处替换', 'filesystem', '{\"type\": \"object\", \"required\": [\"path\", \"edits\"], \"properties\": {\"path\": {\"type\": \"string\", \"description\": \"文件路径\"}, \"edits\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"required\": [\"oldText\", \"newText\"], \"properties\": {\"newText\": {\"type\": \"string\"}, \"oldText\": {\"type\": \"string\"}}}, \"description\": \"替换操作列表\"}}}', '{\"type\": \"object\", \"properties\": {\"error\": {\"type\": \"string\"}, \"success\": {\"type\": \"boolean\"}, \"replacements\": {\"type\": \"integer\"}}}', 'medium', 1, '1.0.0', 30, '{\"readOnlyHint\": false, \"openWorldHint\": false, \"idempotentHint\": true, \"destructiveHint\": false}', 0, '2026-06-13 23:33:47', '2026-06-13 23:33:47');
INSERT INTO `tool` VALUES (5, 'git_status', 'Git 状态', '查看当前 Git 仓库状态（修改/新增/删除的文件）', 'git', '{\"type\": \"object\", \"properties\": {\"repo_path\": {\"type\": \"string\", \"default\": \".\", \"description\": \"仓库路径\"}}}', '{\"type\": \"object\", \"properties\": {\"added\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}}, \"branch\": {\"type\": \"string\"}, \"deleted\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}}, \"modified\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}}, \"untracked\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}}}}', 'low', 1, '1.0.0', 15, '{\"readOnlyHint\": true, \"openWorldHint\": false, \"idempotentHint\": true, \"destructiveHint\": false}', 0, '2026-06-13 23:33:47', '2026-06-13 23:33:47');
INSERT INTO `tool` VALUES (6, 'git_diff', 'Git 差异', '查看文件变更差异（暂存区或指定提交）', 'git', '{\"type\": \"object\", \"properties\": {\"commit\": {\"type\": \"string\", \"description\": \"指定 commit hash（可选）\"}, \"staged\": {\"type\": \"boolean\", \"default\": false}, \"file_path\": {\"type\": \"string\", \"description\": \"指定文件（可选）\"}, \"repo_path\": {\"type\": \"string\", \"default\": \".\"}}}', '{\"type\": \"object\", \"properties\": {\"diff\": {\"type\": \"string\"}, \"files_changed\": {\"type\": \"integer\"}}}', 'low', 1, '1.0.0', 15, '{\"readOnlyHint\": true, \"openWorldHint\": false, \"idempotentHint\": true, \"destructiveHint\": false}', 0, '2026-06-13 23:33:47', '2026-06-13 23:33:47');
INSERT INTO `tool` VALUES (7, 'git_commit', 'Git 提交', '暂存并提交文件变更到 Git 仓库', 'git', '{\"type\": \"object\", \"required\": [\"message\"], \"properties\": {\"files\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}, \"description\": \"要提交的文件列表，空则暂存所有变更\"}, \"message\": {\"type\": \"string\", \"description\": \"提交信息\"}, \"repo_path\": {\"type\": \"string\", \"default\": \".\"}}}', '{\"type\": \"object\", \"properties\": {\"error\": {\"type\": \"string\"}, \"success\": {\"type\": \"boolean\"}, \"commit_hash\": {\"type\": \"string\"}}}', 'medium', 1, '1.0.0', 30, '{\"readOnlyHint\": false, \"openWorldHint\": false, \"idempotentHint\": true, \"destructiveHint\": false}', 0, '2026-06-13 23:33:47', '2026-06-13 23:33:47');
INSERT INTO `tool` VALUES (8, 'git_log', 'Git 日志', '查看 Git 提交历史', 'git', '{\"type\": \"object\", \"properties\": {\"limit\": {\"type\": \"integer\", \"default\": 10}, \"file_path\": {\"type\": \"string\", \"description\": \"限定某个文件的历史\"}, \"repo_path\": {\"type\": \"string\", \"default\": \".\"}}}', '{\"type\": \"object\", \"properties\": {\"commits\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"properties\": {\"date\": {\"type\": \"string\"}, \"hash\": {\"type\": \"string\"}, \"author\": {\"type\": \"string\"}, \"message\": {\"type\": \"string\"}}}}}}', 'low', 1, '1.0.0', 15, '{\"readOnlyHint\": true, \"openWorldHint\": false, \"idempotentHint\": true, \"destructiveHint\": false}', 0, '2026-06-13 23:33:47', '2026-06-13 23:33:47');
INSERT INTO `tool` VALUES (9, 'exec_command', '执行命令', '在沙箱中执行 Shell 命令（受限环境，无网络）', 'shell', '{\"type\": \"object\", \"required\": [\"command\"], \"properties\": {\"command\": {\"type\": \"string\", \"description\": \"要执行的命令\"}, \"timeout\": {\"type\": \"integer\", \"default\": 10, \"description\": \"超时秒数\"}, \"workdir\": {\"type\": \"string\", \"description\": \"工作目录\"}}}', '{\"type\": \"object\", \"properties\": {\"error\": {\"type\": \"string\"}, \"stderr\": {\"type\": \"string\"}, \"stdout\": {\"type\": \"string\"}, \"exit_code\": {\"type\": \"integer\"}}}', 'high', 1, '1.0.0', 30, '{\"readOnlyHint\": false, \"openWorldHint\": false, \"idempotentHint\": false, \"destructiveHint\": true}', 0, '2026-06-13 23:33:47', '2026-06-13 23:33:47');
INSERT INTO `tool` VALUES (10, 'web_fetch', '网页抓取', '抓取 URL 内容并提取为可读文本（Markdown 格式）', 'web', '{\"type\": \"object\", \"required\": [\"url\"], \"properties\": {\"url\": {\"type\": \"string\", \"description\": \"目标 URL\"}, \"max_chars\": {\"type\": \"integer\", \"default\": 10000, \"description\": \"最大返回字符数\"}, \"extract_mode\": {\"enum\": [\"markdown\", \"text\"], \"type\": \"string\", \"default\": \"markdown\"}}}', '{\"type\": \"object\", \"properties\": {\"error\": {\"type\": \"string\"}, \"title\": {\"type\": \"string\"}, \"content\": {\"type\": \"string\"}}}', 'low', 1, '1.0.0', 30, '{\"readOnlyHint\": true, \"openWorldHint\": true, \"idempotentHint\": true, \"destructiveHint\": false}', 0, '2026-06-13 23:33:47', '2026-06-13 23:33:47');
INSERT INTO `tool` VALUES (11, 'memory_save', '保存记忆', '将重要信息保存到长期记忆（MEMORY.md 或 memory/ 目录）', 'memory', '{\"type\": \"object\", \"required\": [\"content\"], \"properties\": {\"tags\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}, \"description\": \"标签\"}, \"content\": {\"type\": \"string\", \"description\": \"要保存的内容\"}, \"category\": {\"enum\": [\"decision\", \"preference\", \"fact\", \"todo\", \"lesson\"], \"type\": \"string\", \"default\": \"fact\"}}}', '{\"type\": \"object\", \"properties\": {\"path\": {\"type\": \"string\"}, \"success\": {\"type\": \"boolean\"}}}', 'low', 1, '1.0.0', 10, '{\"readOnlyHint\": false, \"openWorldHint\": false, \"idempotentHint\": false, \"destructiveHint\": false}', 0, '2026-06-13 23:33:47', '2026-06-13 23:33:47');
INSERT INTO `tool` VALUES (12, 'memory_search', '搜索记忆', '语义搜索长期记忆中的相关信息', 'memory', '{\"type\": \"object\", \"required\": [\"query\"], \"properties\": {\"query\": {\"type\": \"string\", \"description\": \"搜索关键词\"}, \"max_results\": {\"type\": \"integer\", \"default\": 5}}}', '{\"type\": \"object\", \"properties\": {\"results\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"properties\": {\"path\": {\"type\": \"string\"}, \"score\": {\"type\": \"number\"}, \"content\": {\"type\": \"string\"}}}}}}', 'low', 1, '1.0.0', 15, '{\"readOnlyHint\": true, \"openWorldHint\": false, \"idempotentHint\": true, \"destructiveHint\": false}', 0, '2026-06-13 23:33:47', '2026-06-13 23:33:47');
INSERT INTO `tool` VALUES (13, 'spawn_agent', '生成子 Agent', '创建独立子 Agent 执行复杂子任务（并行/隔离）', 'sessions', '{\"type\": \"object\", \"required\": [\"task\"], \"properties\": {\"mode\": {\"enum\": [\"run\", \"session\"], \"type\": \"string\", \"default\": \"run\", \"description\": \"run=一次性，session=持久\"}, \"task\": {\"type\": \"string\", \"description\": \"子任务描述\"}, \"label\": {\"type\": \"string\", \"description\": \"任务标签\"}, \"timeout\": {\"type\": \"integer\", \"default\": 300, \"description\": \"超时秒数\"}}}', '{\"type\": \"object\", \"properties\": {\"status\": {\"type\": \"string\"}, \"session_id\": {\"type\": \"string\"}}}', 'medium', 1, '1.0.0', 600, '{\"readOnlyHint\": false, \"openWorldHint\": false, \"idempotentHint\": false, \"destructiveHint\": false}', 0, '2026-06-13 23:33:47', '2026-06-13 23:33:47');
INSERT INTO `tool` VALUES (14, 'list_sessions', '列出会话', '列出当前活跃的会话和子 Agent', 'sessions', '{\"type\": \"object\", \"properties\": {\"limit\": {\"type\": \"integer\", \"default\": 20}, \"active_minutes\": {\"type\": \"integer\", \"description\": \"只显示最近 N 分钟活跃的会话\"}}}', '{\"type\": \"object\", \"properties\": {\"sessions\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"properties\": {\"key\": {\"type\": \"string\"}, \"kind\": {\"type\": \"string\"}, \"last_message\": {\"type\": \"string\"}}}}}}', 'low', 1, '1.0.0', 10, '{\"readOnlyHint\": true, \"openWorldHint\": false, \"idempotentHint\": true, \"destructiveHint\": false}', 0, '2026-06-13 23:33:47', '2026-06-13 23:33:47');
INSERT INTO `tool` VALUES (15, 'send_message', '发送消息', '向指定渠道或用户发送消息（Telegram/Discord/微信等）', 'messaging', '{\"type\": \"object\", \"required\": [\"message\"], \"properties\": {\"target\": {\"type\": \"string\", \"description\": \"目标用户/群组\"}, \"channel\": {\"type\": \"string\", \"description\": \"目标渠道\"}, \"message\": {\"type\": \"string\", \"description\": \"消息内容\"}}}', '{\"type\": \"object\", \"properties\": {\"success\": {\"type\": \"boolean\"}, \"message_id\": {\"type\": \"string\"}}}', 'medium', 1, '1.0.0', 15, '{\"readOnlyHint\": false, \"openWorldHint\": true, \"idempotentHint\": false, \"destructiveHint\": false}', 0, '2026-06-13 23:33:47', '2026-06-13 23:33:47');
INSERT INTO `tool` VALUES (16, 'image_generate', '生成图片', '根据文字描述生成图片（DALL-E/Midjourney 等）', 'media', '{\"type\": \"object\", \"required\": [\"prompt\"], \"properties\": {\"size\": {\"type\": \"string\", \"default\": \"1024x1024\"}, \"style\": {\"type\": \"string\", \"description\": \"风格\"}, \"prompt\": {\"type\": \"string\", \"description\": \"图片描述\"}}}', '{\"type\": \"object\", \"properties\": {\"url\": {\"type\": \"string\"}, \"error\": {\"type\": \"string\"}}}', 'low', 1, '1.0.0', 120, '{\"readOnlyHint\": false, \"openWorldHint\": true, \"idempotentHint\": false, \"destructiveHint\": false}', 0, '2026-06-13 23:33:47', '2026-06-13 23:33:47');
INSERT INTO `tool` VALUES (17, 'text_to_speech', '语音合成', '将文本转换为语音（TTS）', 'media', '{\"type\": \"object\", \"required\": [\"text\"], \"properties\": {\"text\": {\"type\": \"string\", \"description\": \"要转换的文本\"}, \"speed\": {\"type\": \"number\", \"default\": 1.0}, \"voice\": {\"type\": \"string\", \"default\": \"alloy\", \"description\": \"语音类型\"}}}', '{\"type\": \"object\", \"properties\": {\"error\": {\"type\": \"string\"}, \"audio_url\": {\"type\": \"string\"}}}', 'low', 1, '1.0.0', 60, '{\"readOnlyHint\": false, \"openWorldHint\": true, \"idempotentHint\": false, \"destructiveHint\": false}', 0, '2026-06-13 23:33:47', '2026-06-13 23:33:47');
INSERT INTO `tool` VALUES (18, 'parse_pdf', '解析 PDF', '提取 PDF 文件中的文本内容', 'media', '{\"type\": \"object\", \"required\": [\"path\"], \"properties\": {\"path\": {\"type\": \"string\", \"description\": \"PDF 文件路径\"}, \"pages\": {\"type\": \"string\", \"description\": \"页码范围，如 1-5\"}}}', '{\"type\": \"object\", \"properties\": {\"error\": {\"type\": \"string\"}, \"content\": {\"type\": \"string\"}, \"page_count\": {\"type\": \"integer\"}}}', 'low', 1, '1.0.0', 30, '{\"readOnlyHint\": true, \"openWorldHint\": false, \"idempotentHint\": true, \"destructiveHint\": false}', 0, '2026-06-13 23:33:47', '2026-06-13 23:33:47');
INSERT INTO `tool` VALUES (19, 'cron_create', '创建定时任务', '创建定时执行的 Cron 任务（提醒/检查/自动化）', 'admin', '{\"type\": \"object\", \"required\": [\"schedule\", \"message\"], \"properties\": {\"name\": {\"type\": \"string\", \"description\": \"任务名称\"}, \"enabled\": {\"type\": \"boolean\", \"default\": true}, \"message\": {\"type\": \"string\", \"description\": \"执行内容\"}, \"schedule\": {\"type\": \"object\", \"description\": \"调度配置（kind: at/every/cron）\"}}}', '{\"type\": \"object\", \"properties\": {\"job_id\": {\"type\": \"string\"}, \"success\": {\"type\": \"boolean\"}}}', 'medium', 1, '1.0.0', 15, '{\"readOnlyHint\": false, \"openWorldHint\": false, \"idempotentHint\": false, \"destructiveHint\": false}', 0, '2026-06-13 23:33:47', '2026-06-13 23:33:47');
INSERT INTO `tool` VALUES (20, 'cron_list', '列出定时任务', '查看所有定时任务及其状态', 'admin', '{\"type\": \"object\", \"properties\": {\"include_disabled\": {\"type\": \"boolean\", \"default\": false}}}', '{\"type\": \"object\", \"properties\": {\"jobs\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"properties\": {\"id\": {\"type\": \"string\"}, \"name\": {\"type\": \"string\"}, \"enabled\": {\"type\": \"boolean\"}, \"schedule\": {\"type\": \"object\"}}}}}}', 'low', 1, '1.0.0', 10, '{\"readOnlyHint\": true, \"openWorldHint\": false, \"idempotentHint\": true, \"destructiveHint\": false}', 0, '2026-06-13 23:33:47', '2026-06-13 23:33:47');
INSERT INTO `tool` VALUES (21, 'skill_search', '搜索技能', '从 ClawHub 搜索可用的 Agent 技能', 'skills', '{\"type\": \"object\", \"required\": [\"query\"], \"properties\": {\"limit\": {\"type\": \"integer\", \"default\": 5}, \"query\": {\"type\": \"string\", \"description\": \"搜索关键词\"}}}', '{\"type\": \"object\", \"properties\": {\"skills\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"properties\": {\"name\": {\"type\": \"string\"}, \"version\": {\"type\": \"string\"}, \"description\": {\"type\": \"string\"}}}}}}', 'low', 1, '1.0.0', 15, '{\"readOnlyHint\": true, \"openWorldHint\": true, \"idempotentHint\": true, \"destructiveHint\": false}', 0, '2026-06-13 23:33:47', '2026-06-13 23:33:47');
INSERT INTO `tool` VALUES (22, 'router_control', '路由控制', '查看或调整 ML 路由器的模型选择策略', 'router', '{\"type\": \"object\", \"required\": [\"action\"], \"properties\": {\"model\": {\"type\": \"string\", \"description\": \"指定模型（override 时）\"}, \"action\": {\"enum\": [\"status\", \"override\", \"reset\"], \"type\": \"string\", \"description\": \"操作类型\"}, \"reason\": {\"type\": \"string\", \"description\": \"覆盖原因\"}}}', '{\"type\": \"object\", \"properties\": {\"route_class\": {\"type\": \"string\"}, \"thinking_mode\": {\"type\": \"string\"}, \"selected_model\": {\"type\": \"string\"}}}', 'medium', 1, '1.0.0', 10, '{\"readOnlyHint\": false, \"openWorldHint\": false, \"idempotentHint\": false, \"destructiveHint\": false}', 0, '2026-06-13 23:33:47', '2026-06-13 23:33:47');
INSERT INTO `tool` VALUES (23, 'session_search', '搜索会话记录', '全文搜索历史会话对话记录', 'sessions', '{\"type\": \"object\", \"required\": [\"query\"], \"properties\": {\"limit\": {\"type\": \"integer\", \"default\": 10}, \"query\": {\"type\": \"string\", \"description\": \"搜索关键词\"}, \"session_key\": {\"type\": \"string\", \"description\": \"限定某个会话\"}}}', '{\"type\": \"object\", \"properties\": {\"results\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"properties\": {\"score\": {\"type\": \"number\"}, \"message\": {\"type\": \"string\"}, \"timestamp\": {\"type\": \"string\"}, \"session_key\": {\"type\": \"string\"}}}}}}', 'low', 1, '1.0.0', 15, '{\"readOnlyHint\": true, \"openWorldHint\": false, \"idempotentHint\": true, \"destructiveHint\": false}', 0, '2026-06-13 23:33:47', '2026-06-13 23:33:47');
INSERT INTO `tool` VALUES (27, 'web_search', '网页搜索', '通过 SearXNG 搜索互联网获取实时信息，搜索服务不可用时，用web_fetch抓取网页内容。', 'web', '{\"type\": \"object\", \"required\": [\"query\"], \"properties\": {\"query\": {\"type\": \"string\", \"description\": \"搜索关键词\"}, \"max_results\": {\"type\": \"integer\", \"default\": 5, \"description\": \"最大结果数\"}}}', '{\"type\": \"object\", \"properties\": {\"error\": {\"type\": \"object\"}, \"results\": {\"type\": \"array\", \"items\": {\"type\": \"object\", \"properties\": {\"url\": {\"type\": \"string\"}, \"title\": {\"type\": \"string\"}, \"snippet\": {\"type\": \"string\"}}}}}}', 'low', 1, '1.0.0', 15, '{\"readOnlyHint\": true, \"openWorldHint\": true, \"idempotentHint\": true, \"destructiveHint\": false}', 0, '2026-06-14 00:09:22', '2026-06-23 03:34:05');
INSERT INTO `tool` VALUES (28, 'execute_code', '执行代码', '在 Docker 沙箱中执行代码（支持 Python/JavaScript，无网络，128MB 内存限制）', 'sandbox', '{\"type\": \"object\", \"required\": [\"language\", \"code\"], \"properties\": {\"code\": {\"type\": \"string\", \"description\": \"要执行的代码\"}, \"language\": {\"enum\": [\"python\", \"javascript\"], \"type\": \"string\", \"description\": \"编程语言\"}}}', '{\"type\": \"object\", \"properties\": {\"error\": {\"type\": \"string\"}, \"stderr\": {\"type\": \"string\"}, \"stdout\": {\"type\": \"string\"}, \"exit_code\": {\"type\": \"integer\"}}}', 'high', 1, '1.0.0', 15, '{\"readOnlyHint\": false, \"openWorldHint\": false, \"idempotentHint\": false, \"destructiveHint\": true}', 0, '2026-06-14 00:09:22', '2026-06-14 00:09:22');
INSERT INTO `tool` VALUES (29, 'query_database', '查询数据库', '执行只读 SELECT 查询（自动防注入，禁止写操作，默认 LIMIT 100）', 'database', '{\"type\": \"object\", \"required\": [\"sql\"], \"properties\": {\"sql\": {\"type\": \"string\", \"description\": \"SQL SELECT 查询语句\"}}}', '{\"type\": \"object\", \"properties\": {\"rows\": {\"type\": \"array\"}, \"count\": {\"type\": \"integer\"}, \"error\": {\"type\": \"string\"}, \"columns\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}}}}', 'medium', 1, '1.0.0', 15, '{\"readOnlyHint\": true, \"openWorldHint\": false, \"idempotentHint\": false, \"destructiveHint\": false}', 0, '2026-06-14 00:09:22', '2026-06-14 00:09:22');

SET FOREIGN_KEY_CHECKS = 1;
